name: empower_ability
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  avatar_glow: ^3.0.1
  awesome_notifications: ^0.9.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.1+1
  flutter_svg: ^2.0.9
  flutter_tts: ^3.8.5
  google_fonts: ^6.1.0
  highlight_text: ^1.7.0
  sizer: ^2.0.15
  speech_to_text: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/icons/
